name: DestinationWeddingsbyLaura.com
favicon: null
layout_spectrum: 0.11390078975819051
typography_spectrum: 0.6720786541700363
title: DestinationWeddingsbyLaura
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5140951697248966
  lightness: 0.11694057588465512
  saturation: 0.3550960775464773
  rhythmicContrast: 0.25583645165897906
purpose: []
